# Generated by Django 5.2.1 on 2025-06-04 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='snippets/files/'),
        ),
        migrations.AddField(
            model_name='snippet',
            name='language',
            field=models.CharField(choices=[('c', 'C'), ('java', 'Java'), ('python', 'Python'), ('javascript', 'Javascript')], default='c', max_length=50),
        ),
        migrations.AddField(
            model_name='snippet',
            name='link_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='snippet',
            name='link_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
