# Generated by Django 5.2.1 on 2025-06-05 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0002_snippet_file_snippet_language_snippet_link_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='content_type',
            field=models.CharField(choices=[('CODE', 'Code'), ('LINKS', 'Links'), ('NOTES', 'Notes'), ('FILES', 'Files')], max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='snippets.category'),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='content_type',
            field=models.CharField(choices=[('CODE', 'Code'), ('LINKS', 'Links'), ('NOTES', 'Notes'), ('FILES', 'Files')], max_length=10),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='language',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='link_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
