# Generated by Django 5.2.1 on 2025-06-05 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0003_alter_category_content_type_alter_snippet_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='collaborators',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='snippets',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='category',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='user',
        ),
        migrations.RemoveField(
            model_name='snippet',
            name='subcategory',
        ),
        migrations.RemoveField(
            model_name='category',
            name='user',
        ),
        migrations.RemoveField(
            model_name='snippet',
            name='user',
        ),
        migrations.AddIndex(
            model_name='snippet',
            index=models.Index(fields=['category'], name='snippets_sn_categor_c9fa00_idx'),
        ),
        migrations.DeleteModel(
            name='Collection',
        ),
        migrations.DeleteModel(
            name='SubCategory',
        ),
    ]
