# Generated by Django 5.2.1 on 2025-06-08 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0005_snippet_user'),
    ]

    operations = [
    ]
