# Generated by Django 5.2.1 on 2025-06-08 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0006_auto_20250608_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='category',
            field=models.CharField(choices=[('CODE', 'Code'), ('LINKS', 'Links'), ('NOTES', 'Notes'), ('FILES', 'Files')], default='CODE', max_length=20),
        ),
        migrations.RenameIndex(
            model_name='snippet',
            new_name='snippets_sn_categor_5af630_idx',
            old_name='snippets_sn_categor_c9fa00_idx',
        ),
        migrations.RemoveField(
            model_name='snippet',
            name='content_type',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
